"use client";
import Link from "next/link";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { ManagedPost } from "@/backend/editorial/management";
import { managePostsAction } from "./management-actions";
import styles from "../studio.module.css";
export function PostsManager({posts,niches,returnTo}:{posts:ManagedPost[];niches:{id:string;name:string}[];returnTo:string}) {
 useEffect(()=>{const key=`studio-position:${returnTo}`;let position:string|null=null;try{position=sessionStorage.getItem(key);}catch{}if(position)window.scrollTo(0,Number(position));const save=()=>{try{sessionStorage.setItem(key,String(window.scrollY));}catch{}};window.addEventListener("scroll",save);return()=>window.removeEventListener("scroll",save);},[returnTo]);
 const [selected,setSelected]=useState<string[]>([]); const [operation,setOperation]=useState("trash");
 const [resultTitles,setResultTitles]=useState<Record<string,string>>({});
 const [results,setResults]=useState<Awaited<ReturnType<typeof managePostsAction>>>([]);const [pending,start]=useTransition();const router=useRouter();
 return <form className={styles.queue} action={form=>start(async()=>{try{setResultTitles(Object.fromEntries(posts.map(post=>[post.id,post.title])));const outcome=await managePostsAction(form);setResults(outcome);setSelected(current=>current.filter(id=>!outcome.some(result=>result.id===id&&result.ok)));router.refresh();}catch(error){setResults([{id:"Selection",ok:false,conflict:false,error:error instanceof Error?error.message:"Operation failed"}]);}})}>
 <fieldset className={styles.postFieldset} disabled={pending}><legend>Select posts to manage</legend>
 {posts.map(post=><article className={styles.postRow} key={post.id}>
 <label className={styles.postSelect}><input type="checkbox" name="selection" aria-label={`Select ${post.title}`} checked={selected.includes(post.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,post.id]:current.filter(id=>id!==post.id))} value={`${post.id}:${post.editorialVersion}`}/></label>
 <div><Link href={`/studio/candidates/${post.id}?returnTo=${encodeURIComponent(returnTo)}`}>{post.title}</Link><p>{niches.find(n=>n.id===post.nicheId)?.name??"Unassigned"} · {post.status==="candidate"?"Inbox candidate":post.status} · {post.mediaId?"Cover selected":"Generated cover"}{post.privateEdits?" · Private edits":""}</p><p>Edited {new Date(post.lastEditedAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Kolkata"})}{post.scheduledFor?` · Scheduled ${new Date(post.scheduledFor).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}`:""}</p>{post.needsReview&&<p className={styles.warning}>Needs review: {post.needsReview}</p>}</div>
 </article>)}
 {!posts.length&&<p>No posts match these filters.</p>}
 {selected.length>0 && <div className={styles.bulkPanel}><strong>{selected.length} selected</strong><p>{operation==="trash"?"Selected posts will leave the public site and scheduled releases. Content stays recoverable in Trash.":operation==="restore"?"Restore as private drafts. Nothing will be published.":operation==="unpublish"?"Remove public visibility and cancel scheduling. Writing is kept.":operation==="cancel_schedule"?"Cancel approved release times. Writing is kept.":operation==="duplicate"?"Create new private copies. Original posts remain unchanged.":"Niche changes stay private until you approve a live update."}</p><ul>{posts.filter(post=>selected.includes(post.id)).map(post=><li key={post.id}>{post.title}</li>)}</ul><button type="button" onClick={()=>setSelected([])}>Clear selection</button><label>Operation <select name="operation" value={operation} onChange={event=>setOperation(event.target.value)}><option value="trash">Move to Trash</option><option value="restore">Restore privately</option><option value="unpublish">Unpublish</option><option value="duplicate">Duplicate privately</option><option value="change_niche">Change private niche</option><option value="cancel_schedule">Cancel schedule</option></select></label>
 {operation==="change_niche" && <label>Niche for change <select name="nicheId"><option value="">Choose niche</option>{niches.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label>}
 <label className={styles.confirmBulk}><input type="checkbox" name="confirmed" required/> Confirm the selected operation for every selected post</label><button type="submit">{pending?"Applying…":"Apply to selection"}</button></div>}
 </fieldset><div role="status">{results.map(r=><p key={r.id}>{resultTitles[r.id]??posts.find(p=>p.id===r.id)?.title??r.id}: {r.ok?<>Saved revision {r.revision}{r.candidateId!==r.id&&<Link href={`/studio/candidates/${r.candidateId}`}> Open copy</Link>}</>:`${r.conflict?"Conflict — ":""}${r.error}`}</p>)}</div></form>;
}
